spring.application.name=mercaditolibre
spring.datasource.url=jdbc:mysql://localhost:3306/mercaditolibre
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#configuracion de hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#configuracion global de cors para react
spring.mvc.cors.allowed-origins=http://localhost:5173
spring.mvc.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS

# Configuración del Token JWT
app.jwt.secret=f3b7e03bef00e8c1594fed64c7122f6c1ea93164ebf832afffb121a6c54b76ce
app.jwt.expiration-ms=86400000

stripe.apikey.secret=${STRIPE_SECRET_KEY}
# Reemplaza las dos líneas anteriores de Stripe por esta sola:
stripe.apikey.secret=

